name: Java CI on main branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Step 3: Scan the repository with Trivy (file system scan)
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'fs-scan.html'
          severity: 'CRITICAL,HIGH'

      # Step 4: Build the Java project using Maven
      - name: Build with Maven
        run: ./mvnw -B verify

      # Step 5: Build the Docker image
      - name: Build Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: gabeokiri/java-petclinic-app
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  trivy_image_scan:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 6: Scan the Docker image with Trivy
      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: gabeokiri/java-petclinic-app:latest
          severity: 'CRITICAL,HIGH'
          exit-code: 1
